name: Release to PyPi

on:
  push:
    tags:
      - "v*.*.*" # Triggers on semver releases tags

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Build package
        run: |
          poetry build

      - name: Verify build with Twine
        run: |
          poetry run twine check dist/*

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry publish --no-interaction --username __token__ --password "$POETRY_PYPI_TOKEN_PYPI"